- hosts: AWS_Instance
  remote_user: ubuntu
  tasks:
    - name: wordpress
      docker_container:
        image: wordpress
        name: wordpress
        ports:
          - "80:80"
        env:
          WORDPRESS_DB_PASSWORD: "12345678"
          WORDPRESS_DB_NAME: mydb
          WORDPRESS_DB_USER: admin
          WORDPRESS_DB_HOST: "{{ mysql_host }}"

