- hosts: AWS_Instance
  remote_user: ubuntu
  tasks:
    - name: wordpress
      docker_container:
        image: wordpress
        name: wordpress
        ports:
          - "8080:80"
        env:
          WORDPRESS_DB_PASSWORD: wordpress
          WORDPRESS_DB_NAME: mydb
          WORDPRESS_DB_USER: wordpress
          WORDPRESS_DB_HOST: "{rds_address}"

