name: Deploy Infrastructure

on:
  push:
  
jobs:
  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3 

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Echo
      run: "echo Success"
      
