## ...
on:
  pull_request:

env:
  TF_CLOUD_ORGANIZATION: "aws_organizations_organization"
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_WORKSPACE: "learn-terraform-github-actions"
  CONFIG_DIRECTORY: "./"
## ...
