name: Deploy Infrastructure

on:
  push:
  
jobs:

  tf_fmt:
    name: Deploy Site
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: ./terraform
    steps:
    - name: Change working directory
      run : pwd 
    - name: Checkout Repo
      uses: actions/checkout@v3 

    - name: Terraform Init
      uses: hashicorp/terraform-github-actions/init@v0.4.0

    - name: Echo
      run: "echo Success"
      
